// src/core/types/parts.ts
export const PART_DISCIPLINE_OPTIONS = [
    { value: "fire-alarm", label: "Fire Alarm" },
    { value: "intruder-alarm", label: "Intruder" },
    { value: "cctv", label: "CCTV" },
    { value: "access-control", label: "Access Control" },
    { value: "emergency-lighting", label: "Emergency Lighting" },
    { value: "other", label: "Other" },
];
export const PART_ACTION_OPTIONS = [
    { value: "add", label: "Add" },
    { value: "replace", label: "Replace" },
    { value: "remove", label: "Remove" },
    { value: "temporary-add", label: "Temporary Add" },
    { value: "return", label: "Return" },
];
export const PART_SOURCE_OPTIONS = [
    { value: "van-stock", label: "Van Stock" },
    { value: "site-stock", label: "Site Stock" },
    { value: "supplier", label: "Supplier" },
    { value: "other", label: "Other" },
];
export const PART_CATEGORY_OPTIONS = {
    "fire-alarm": [
        "detector",
        "base",
        "mcp",
        "sounder",
        "sounder-beacon",
        "interface",
        "io",
        "panel-part",
        "psu",
        "cable",
        "other",
    ],
    "intruder-alarm": [
        "pir",
        "contact",
        "shock",
        "keypad",
        "expander",
        "panel-part",
        "bell",
        "psu",
        "signalling",
        "cable",
        "other",
    ],
    cctv: [
        "camera",
        "nvr",
        "switch",
        "psu",
        "injector",
        "storage",
        "networking",
        "mount",
        "housing",
        "cable",
        "other",
    ],
    "access-control": [
        "reader",
        "controller",
        "lock",
        "maglock",
        "exit-button",
        "break-glass",
        "door-contact",
        "psu",
        "cable",
        "other",
    ],
    "emergency-lighting": [
        "fitting",
        "battery",
        "driver",
        "test-key",
        "sign",
        "cable",
        "other",
    ],
    other: ["other"],
};
