export const FIRE_DEVICE_TYPES = [
    "optical_detector",
    "heat_detector",
    "multi_detector",
    "beam_detector",
    "aspirating_point",
    "mcp",
    "sounder",
    "sounder_base",
    "input_module",
    "output_module",
    "interface",
    "panel",
    "psu",
    "other",
];
export const FIRE_DEVICE_TYPE_LABELS = {
    optical_detector: "Optical Detector",
    heat_detector: "Heat Detector",
    multi_detector: "Multi Sensor Detector",
    beam_detector: "Beam Detector",
    aspirating_point: "Aspirating Detection Point",
    mcp: "Manual Call Point",
    sounder: "Sounder",
    sounder_base: "Sounder Base",
    input_module: "Input Module",
    output_module: "Output Module",
    interface: "Interface Module",
    panel: "Fire Alarm Panel",
    psu: "Power Supply Unit",
    other: "Other Device",
};
